### PR TITLE
added 404.html

### PR DESCRIPTION
**Pull request by ankita132**

### CODE REVIEW

**Comment by americast** [comment]
Sorry, didn't notice this was not meant for `master`. Anyway, what was this? :thinking:

**Comment by ankita132** [comment]
it was for @dibyadas to integrate with the backend and then create a pr to master branch

**Comment by americast** [comment]
Peace! @dibyadas Kindly find the code in the branch `ankita`.

**Comment by dibyadas** [comment]
@americast will do

**Pull request merged**
