### PR TITLE
Revert "projects: add Sandeep's project"

### PR DESCRIPTION
**Pull request by pranitbauva1997**
There is something wrong that I have done which I don't know. Please can anyone finish this? There seems to be some problems with the line endings but I don't know what exactly.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
The projects page looks fine with updated Diginehru project. I can't spot the error and the reason why you are reverting this.

I also got some weird `^M` line endings which I could see in `git diff`. Turns out the reason is because someone amongst us is on Windows.
Windows uses `\r\n` for line endings while unix uses `\n`. Now, smart editors eventually read/replace `\r` with `^M` (ctrl + M) on Unix based systems. But I'm not sure if any errors are caused by it.

Fix : Even if you are on Windows, change the default line endings to `\n`. In vim, you can do `:set ff=unix`. In Sublime, you can add the following in settings. `"default_line_ending": "unix"`

**Comment by pranitbauva1997** [comment]
@OrkoHunter I tried running it locally before sending a PR, and the project showed up at that time, thus I merged it. After that I deployed the script and it isn't showing in my browser now.

2017-11-27-005130_1366x768_scrot

If this is showing in your browser, well and good, we can close the PR! There might be some browser cache which is creating problems for me.

**Comment by OrkoHunter** [comment]
Fixed in #113 Try searching now.

**Comment by OrkoHunter** [comment]
Do a hard refresh as well.

**Comment by pranitbauva1997** [comment]
@OrkoHunter Thanks! It works now :)

**Pull request closed without merging**
