### PR TITLE
added manuals

### PR DESCRIPTION
**Pull request by sangeet259**
The links were incorrect, added the manuals in the static/files and linked the manuals there.

### CODE REVIEW

**Comment by sangeet259** [comment]
Fixes #43

**Comment by pranitbauva1997** [comment]
What about `http://kwoc.kossiitkgp.in/mentor_form`?

**Comment by sangeet259** [comment]
@pranitbauva1997  I didn't get that. The manual mentions the steps to add projects!

**Comment by pranitbauva1997** [comment]
Thanks!

**Pull request merged**
