### PR TITLE
Testimonials

### PR DESCRIPTION
**Pull request by ankita132**

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
This needs rebase. Please just use `git rebase -i` and remove the unnecessary commits.

**Comment by nitinkgp23** [comment]
@ankita132 Is this to be closed?

**Comment by nitinkgp23** [comment]
@ankita132 Is this to be closed?

**Comment by ankita132** [comment]
@nitinkgp23 yes

**Comment by nitinkgp23** [comment]
Also, try solving the conflict from next time ;). I know it is a strenous task, but you will get to learn :)

**Pull request closed without merging**
